# Generated by Django 5.1.3 on 2024-11-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], max_length=50, null=True),
        ),
    ]
