# Generated by Django 5.1.3 on 2024-11-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_levels_alter_customuser_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='levels',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
