# Generated by Django 5.1.3 on 2024-11-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('arcade', 'Arcade'), ('cosmetic_store', 'Cosmetic Store'), ('salon', 'Salon'), ('fashion', 'Boutique'), ('spa', 'Spa'), ('lounge', 'Lounge'), ('all', 'All')], default='none', max_length=50, null=True),
        ),
    ]
