# Generated by Django 5.1.3 on 2024-11-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_remove_inventory_barcode_remove_inventory_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
