# Generated by Django 5.1.3 on 2024-12-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='type',
            field=models.CharField(choices=[('Take Away', 'Take Away'), ('Dine In', 'Dine In')], default='Dine In', max_length=100),
            preserve_default=False,
        ),
    ]
