# Generated by Django 5.1.3 on 2024-12-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resturant', '0002_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Table_no',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
