# Generated by Django 5.1.3 on 2024-12-14 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resturant', '0004_remove_inventory_description_remove_inventory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='waiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resturant_waiter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
