# Generated by Django 5.1.3 on 2024-11-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_store', '0002_rename_price_inventory_cost_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='selling_price',
            new_name='price',
        ),
    ]
