# Generated by Django 5.1.3 on 2024-12-07 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetic_store', '0003_rename_selling_price_inventory_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='icon',
        ),
        migrations.AddField(
            model_name='day',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='brand',
            field=models.CharField(default='2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='buying_unit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='code',
            field=models.CharField(default='453', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='qty_per_buying_unit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventory',
            name='selling_unit',
            field=models.CharField(default='3', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='size',
            field=models.CharField(default='33', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('refunded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_refunded_by', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_refunds', to='cosmetic_store.sale')),
            ],
        ),
    ]
