# Generated by Django 5.1.3 on 2024-11-28 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
    ]
